"""
Assetman
-----------------

This is a library for generic large asset handling which uses S3 as a storage mechanism.

The motivation behind this library is to provide a service for easy handling of blob type data
that does not fit well into other typical datastores (relational or otherwise).

The library will eventually include tie-ins for setting up CloudFront as a CDN for the content
being stored here in an effort to ease and separate load from the main body of the application
that is loading the content.

To be clear-- the application is responsible for storing / retrieving / tracking the UUIDs
generated by the content storage process however this library does handle and provide an interface
for important things like cache times, metadata, mimetypes, security and so forth.

This library uses the boto library for Amazon S3 and CloudFront support.
	
"""

from setuptools import setup, find_packages

setup(
	name='assetman',
	version='0.1',
	url='http://github.com/petermelias/assetman',
	license='BSD',
	author='Peter M. Elias',
	author_email='petermelias@gmail.com',
	description='Generic blob-data asset manager that uses S3 for storage and CloudFront for delivery.',
	long_description=__doc__,
	packages=find_packages(),
	zip_safe=False,
	include_package_data=True,
	platforms='any',
	install_requires=[
		'boto',
		'nose'
	],
	classifiers=[
		'Environment :: Web Environment',
		'Intended Audience :: Developers',
		'License :: OSI Approved :: BSD License',
		'Operating System :: OS Independent',
		'Programming Language :: Python',
		'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
		'Topic :: Software Development :: Libraries :: Python Modules'
	],
)